services:
  mysql:
    image: mysql:8.0
    container_name: task-management
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: task_management
    ports:
      - "3307:3306"

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025" # Web interface
      - "1025:1025" # SMTP server
